spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company
    username: user
    password: letmein
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO